<?php include("superglobalheader.php"); ?>
<?php include("php/nav.php"); ?>
<!-- added class striped to table -->
<table class="striped" border="1">
    <tbody>
        <thead>
        
       
                <tr>
            <td>
                <b>Student</b>
            </td>
            <td>
                <b>Educational Background</b>
            </td>
            <td>
                <b>Current BSE Technique</b>
            </td>
            <td>
                <b>Current CBE Technique</b>
            </td>
            <td>
                <b>Normal Breast Structure</b>
            </td>
            <td>
                <b>Normal Changes in the Breast</b>
            </td>
            <td>
                <b>Disorders of the Breast</b>
            </td>
            <td>
                <b>Development of Breast Cancer</b>
            </td>
            <td>
                <b>Breast Cancer Screening </b>
            </td>
            <td>
                <b>Clinical History and Physical Examination </b>
            </td>
            <td>
                <b>Post-Screening Follow-Up and Diagnostic Procedures</b>
            </td>
            <td>
                <b>Research History of MammaCare </b>
            </td>
            <td>
                <b>The 5 Ps Quiz</b>
            </td>
            <td>
                <b>CBE ONLINE Evaluation</b>
            </td>
            <td>
                <b>CBE Simulator-Trainer Evaluation</b>
            </td>
            <td>
                <b>Final Grade</b>
            </td>
        </tr>
         </thead>
        <tr>
            <td>bufaculty01</td>
            <td></td>
            <td></td>
            <td></td>
            <td>50</td>
            <td>75</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>62.5</b>
            </td>
        </tr>
        <tr>
            <td>bufaculty02</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bufaculty03</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse01</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>83.33</b>
            </td>
        </tr>
        <tr>
            <td>bunurse02</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>91.67</b>
            </td>
        </tr>
        <tr>
            <td>bunurse03</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>97.22</b>
            </td>
        </tr>
        <tr>
            <td>bunurse04</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>100</td>
            <td>50</td>
            <td>75</td>
            <td>50</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>68.52</b>
            </td>
        </tr>
        <tr>
            <td>bunurse05</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>25</td>
            <td>100</td>
            <td>50</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>60.19</b>
            </td>
        </tr>
        <tr>
            <td>bunurse06</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>86.11</b>
            </td>
        </tr>
        <tr>
            <td>bunurse07</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse08</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>88.89</b>
            </td>
        </tr>
        <tr>
            <td>bunurse09</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>90.74</b>
            </td>
        </tr>
        <tr>
            <td>bunurse10</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>25</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>25</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>63.89</b>
            </td>
        </tr>
        <tr>
            <td>bunurse100</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse11</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>25</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>74.07</b>
            </td>
        </tr>
        <tr>
            <td>bunurse12</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>72.22</b>
            </td>
        </tr>
        <tr>
            <td>bunurse13</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>92.59</b>
            </td>
        </tr>
        <tr>
            <td>bunurse14</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>33.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>78.7</b>
            </td>
        </tr>
        <tr>
            <td>bunurse15</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>100</td>
            <td>75</td>
            <td>0</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>66.67</b>
            </td>
        </tr>
        <tr>
            <td>bunurse16</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>50</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>80.56</b>
            </td>
        </tr>
        <tr>
            <td>bunurse17</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>97.22</b>
            </td>
        </tr>
        <tr>
            <td>bunurse18</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>50</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>69.44</b>
            </td>
        </tr>
        <tr>
            <td>bunurse19</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>81.48</b>
            </td>
        </tr>
        <tr>
            <td>bunurse20</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>25</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>69.44</b>
            </td>
        </tr>
        <tr>
            <td>bunurse21</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>94.44</b>
            </td>
        </tr>
        <tr>
            <td>bunurse22</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td></td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>96.88</b>
            </td>
        </tr>
        <tr>
            <td>bunurse23</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>78.7</b>
            </td>
        </tr>
        <tr>
            <td>bunurse24</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>76.85</b>
            </td>
        </tr>
        <tr>
            <td>bunurse25</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>66.67</b>
            </td>
        </tr>
        <tr>
            <td>bunurse26</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse27</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse28</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse29</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse30</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>16.66667</td>
            <td></td>
            <td>y</td>
            <td>
                <b>74.07</b>
            </td>
        </tr>
        <tr>
            <td>bunurse31</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse32</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse33</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse34</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>86.11</b>
            </td>
        </tr>
        <tr>
            <td>bunurse35</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75//td>
                <td>100</td>
                <td>75</td>
                <td>83.33333</td>
                <td>y</td>
                <td>y</td>
                <td>
                    <b>84.26</b>
                </td>
        </tr>
        <tr>
            <td>bunurse36</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>97.22</b>
            </td>
        </tr>
        <tr>
            <td>bunurse37</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>92.59</b>
            </td>
        </tr>
        <tr>
            <td>bunurse38</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>83.33</b>
            </td>
        </tr>
        <tr>
            <td>bunurse39</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>75</td>
            <td>100</td>
            <td>50</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>74.07</b>
            </td>
        </tr>
        <tr>
            <td>bunurse40</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>50</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>33.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>73.15</b>
            </td>
        </tr>
        <tr>
            <td>bunurse41</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>62.96</b>
            </td>
        </tr>
        <tr>
            <td>bunurse42</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>85.19</b>
            </td>
        </tr>
        <tr>
            <td>bunurse43</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>80.56</b>
            </td>
        </tr>
        <tr>
            <td>bunurse44</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>87.04</b>
            </td>
        </tr>
        <tr>
            <td>bunurse45</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>89.81</b>
            </td>
        </tr>
        <tr>
            <td>bunurse46</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>50</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>25</td>
            <td>83.33333</td>
            <td>y</td>
            <td></td>
            <td>
                <b>73.15</b>
            </td>
        </tr>
        <tr>
            <td>bunurse47</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>50</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>50</td>
            <td>50</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>70.37</b>
            </td>
        </tr>
        <tr>
            <td>bunurse48</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>75</td>
            <td>25</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>25</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>52.78</b>
            </td>
        </tr>
        <tr>
            <td>bunurse49</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>86.11</b>
            </td>
        </tr>
        <tr>
            <td>bunurse50</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>89.81</b>
            </td>
        </tr>
        <tr>
            <td>bunurse51</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>83.33</b>
            </td>
        </tr>
        <tr>
            <td>bunurse52</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>75</td>
            <td>25</td>
            <td>100</td>
            <td>50</td>
            <td>25</td>
            <td>100</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>64.81</b>
            </td>
        </tr>
        <tr>
            <td>bunurse53</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse54</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse55</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse56</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse57</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse58</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse59</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse60</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse61</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse62</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse63</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse64</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse65</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse66</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse67</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>90.74</b>
            </td>
        </tr>
        <tr>
            <td>bunurse68</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>91.67</b>
            </td>
        </tr>
        <tr>
            <td>bunurse69</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>25</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>84.26</b>
            </td>
        </tr>
        <tr>
            <td>bunurse70</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>100</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>76.85</b>
            </td>
        </tr>
        <tr>
            <td>bunurse71</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>25</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>69.44</b>
            </td>
        </tr>
        <tr>
            <td>bunurse72</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>69.44</b>
            </td>
        </tr>
        <tr>
            <td>bunurse73</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>50</td>
            <td>100</td>
            <td>25</td>
            <td>50</td>
            <td>0</td>
            <td>100</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>61.11</b>
            </td>
        </tr>
        <tr>
            <td>bunurse74</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>50</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>78.7</b>
            </td>
        </tr>
        <tr>
            <td>bunurse75</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>89.81</b>
            </td>
        </tr>
        <tr>
            <td>bunurse76</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>95.37</b>
            </td>
        </tr>
        <tr>
            <td>bunurse77</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>79.63</b>
            </td>
        </tr>
        <tr>
            <td>bunurse78</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>89.81</b>
            </td>
        </tr>
        <tr>
            <td>bunurse79</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>50</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>33.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>67.59</b>
            </td>
        </tr>
        <tr>
            <td>bunurse80</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>100</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>93.52</b>
            </td>
        </tr>
        <tr>
            <td>bunurse81</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>50</td>
            <td>100</td>
            <td>75</td>
            <td>50</td>
            <td>50</td>
            <td>100</td>
            <td>25</td>
            <td>66.66667</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>65.74</b>
            </td>
        </tr>
        <tr>
            <td>bunurse82</td>
            <td>y</td>
            <td>y</td>
            <td>y</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>75</td>
            <td>75</td>
            <td>75</td>
            <td>100</td>
            <td>100</td>
            <td>83.33333</td>
            <td>y</td>
            <td>y</td>
            <td>
                <b>84.26</b>
            </td>
        </tr>
        <tr>
            <td>bunurse83</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse84</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse85</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse86</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse87</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse88</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse89</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse90</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse91</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse92</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse93</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse94</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse95</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse96</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse97</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse98</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
        <tr>
            <td>bunurse99</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <b>0</b>
            </td>
        </tr>
    </tbody>
</table>


<!-- Please include this before the closing body tag -->
<?php include("php/navfoot.php"); ?>
<?php include("superfooter.php"); ?>

